// <auto-generated />
namespace TP.WL.ERP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update3));
        
        string IMigrationMetadata.Id
        {
            get { return "202110190215451_update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
